myproject/models.py
import datetime

from myproject import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(64), nullable=False, default='default_profile.png')
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('BlogPost', backref='author', lazy=True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password = password

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"Username - {self.username}"


class BlogPost(db.Model):
    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    date = db.Column(db.DateTime, nullable=False, default=datetime.UTCnow)

    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} -- Date: {self.date} -- {self.title}"

myproject/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from myproject.models import User


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in')


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='passwords must '
                                                                                                     'match')])
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already')

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('username has been registered already')


class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Update profile picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def check_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already')

    def check_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('username has been registered already')

myproject/__init__.py
from flask import Flask
import os
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
app.config['SQL_TRACK_MODIFICATION'] = False

db = SQLAlchemy(app)
Migrate(app, db)


login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'

from myproject.core.views import core
from myproject.error_pages.handlers import error_pages
from myproject.user.views import users

app.register_blueprint(core)
app.register_blueprint(error_pages)
app.register_blueprint(users)

myproject/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

myproject/user/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myproject import db
from myproject.models import User, BlogPost
from myproject.user.forms import RegistrationForm, LoginForm, UpdateUserForm
from myproject.user.picture_handler import add_profile_pic

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration')
        return redirect(url_for('user.login'))
    return render_template('register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

myproject/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Puppy Company Blog</h1>
</div>
{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <ul class="nav">
    <li class="nav-link">
      <a href="{{url_for('core.index')}}">Home</a>
    </li>

    <li class="nav-link">
      <a href="{{url_for('core.info')}}">About</a>
    </li>

    <li class="nav-link">
      <a href="#">Logout</a>
    </li>

    <li class="nav-link">
      <a href="#">Account</a>
    </li>

    <li class="nav-link">
      <a href="#">Create Post</a>
    </li>

    <li class="nav-link">
      <a href="#">Log in</a>
    </li>

    <li class="nav-link">
      <a href="#">Register</a>
    </li>
  </ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>

</body>
</html>

myproject/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
  </div>
{% endblock %}

myproject/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Info about the company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias consectetur corporis, cum cumque deleniti distinctio enim ex facere facilis fuga illo incidunt optio pariatur provident qui quo, reiciendis suscipit? Dolorem.</p>
  </div>
{% endblock %}

myproject/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
  {{form.hidden_tag()}}
  {{form.email.label}}{{form.email}}<br>
  {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
  {{form.submit()}}
</form>
{% endblock %}

myproject/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
  {{form.hidden_tag()}}
  {{form.email.label}}{{form.email}}<br>
  {{form.username.label}}{{form.username}}<br>
  {{form.password.label}}{{form.password}}<br>
  {{form.pass_confirm.label}}{{form.pass_confirm}}<br>
  {{form.submit()}}
</form>
{% endblock %}